// registration
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_INIT = 'REGISTER_USER_INIT'

// login
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_INIT = 'LOGIN_USER_INIT';

// logout
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// Places
export const GET_PLACE_REQUEST = 'GET_PLACE_REQUEST'
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS'

export const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST'
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS'

export const ADD_PLACE_REQUEST = 'ADD_PLACE_REQUEST'
export const ADD_PLACE_FAILURE = 'ADD_PLACE_FAILURE'

export const DELETE_PLACE_REQUEST = 'DELETE_PLACES_REQUEST'

export const PLACE_INIT = 'PLACE_INIT'

// Reviews
export const GET_ALL_REVIEWS_REQUEST = 'GET_ALL_REVIEWS_REQUEST'
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST'
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'

// Images
export const GET_ALL_IMAGES_REQUEST = 'GET_ALL_IMAGES_REQUEST'
export const GET_ALL_IMAGES_SUCCESS = 'GET_ALL_IMAGES_SUCCESS'

export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST'
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'

export const ADD_IMAGE_REQUEST = 'ADD_IMAGE_REQUEST'
export const ADD_IMAGE_FAILURE = 'ADD_IMAGE_FAILURE'

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST'


